services:
  - type: web
    name: insurance-comparison
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn a_core.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.2
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com