# Generated by Django 5.1.2 on 2024-12-03 04:18

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=200)),
                ('monthly_premium', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('deductible', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('out_of_pocket_max', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('network_info', models.TextField(help_text='Detailed information about the provider network')),
                ('prescription_coverage', models.TextField(help_text='Description of prescription drug coverage and tiers')),
                ('benefits', models.JSONField(help_text='JSON object containing covered benefits and their details')),
                ('additional_features', models.TextField(blank=True, help_text='Any additional plan features or benefits')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['monthly_premium', 'provider'],
                'indexes': [models.Index(fields=['provider'], name='marketplace_provide_535c90_idx'), models.Index(fields=['monthly_premium'], name='marketplace_monthly_ecaca2_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Session identifier for anonymous users', max_length=100, unique=True)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('zip_code', models.CharField(default='00000', help_text='5-digit ZIP code for location-based results', max_length=5)),
                ('current_insurance', models.BooleanField(default=False, help_text='Whether the user currently has insurance')),
                ('coverage_start_date', models.DateField(default=django.utils.timezone.now, help_text='Desired start date for new coverage')),
                ('doctor_visit_frequency', models.CharField(choices=[('rarely', 'Rarely (0-1 times per year)'), ('occasionally', 'Occasionally (2-3 times per year)'), ('regularly', 'Regularly (4-6 times per year)'), ('frequently', 'Frequently (7+ times per year)')], default='occasionally', help_text='How often the user typically visits doctors', max_length=20)),
                ('has_medical_conditions', models.BooleanField(default=False)),
                ('needs_prescription_coverage', models.BooleanField(default=False)),
                ('planned_procedures', models.TextField(blank=True)),
                ('needs_specialist_visits', models.BooleanField(default=False)),
                ('max_monthly_premium', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('preferred_deductible', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('preferred_max_out_of_pocket', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('desired_benefits', models.JSONField(default=list, help_text='JSON array of desired benefits and coverage features')),
                ('preferred_providers', models.TextField(blank=True)),
                ('preferred_hospitals', models.TextField(blank=True)),
                ('preferred_pharmacies', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_plans', models.ManyToManyField(blank=True, related_name='interested_users', to='marketplace.insuranceplan')),
            ],
            options={
                'verbose_name_plural': 'User Preferences',
                'indexes': [models.Index(fields=['session_id'], name='marketplace_session_e15ac5_idx'), models.Index(fields=['zip_code'], name='marketplace_zip_cod_9216d0_idx'), models.Index(fields=['created_at'], name='marketplace_created_77796c_idx')],
            },
        ),
    ]
